# Generated by Django 5.2.8 on 2025-11-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
