# Generated by Django 5.2.8 on 2025-11-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='public',
        ),
    ]
