# Generated by Django 5.2.8 on 2025-11-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_remove_tweet_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
